language: python
python:
- 3.6
sudo: required
services:
- docker
install:
- make dev-env
script:
- make build-test-all DARGS="--build-arg TEST_ONLY_BUILD=1"
env:
  global:
  - secure: I9Pnv/bgTQ7vYFsmkhdV/5hQYIpOxB3v6zEgUMd2ZjCyRvwuO2UgLpYjLV4nz6wpLzRg/Avos3eCUWCMQnPrjlfOO8NqQ9peGHIgXACco8L4x9bDLWENGH4bK5r6Cg9dLIzrn5KriPiBm7TBpd1MLJ8juKPU1ASRMmbZ08pQClwNOToifb3xG4BIf8YLVXDnx7l/sHOsP3a13g/ef1jvcaEUwnZzZ7/XqwUWeWHjmJr3hmH1fkl4F0ChEzWSu20df/PoHtrLj8nx7SrqyYreAN7F1YTxL248CdTzav/s3QKgkoksS8fSxuh8D4/r8sr3rKZy2fXWAC9W9HI5QK1AtwaLy3QdQTdCPQrfJjOfAUKLZb8IDj2mU2MnmhEisyjbnZdeEtXbLVdAFD3eFP8sweqo2cZzOC3K0BH+L1VyHEGq3ZPZk+anICzI99AMNkL7cl4BMVjpWFZVj0zY3ZNgqVEJar9UeuLkJxqozQMtpH1sSBHYxg3yaLLTtcjbfHsbnC/aY4F1WcoNFUZkyykigTMwsRxlyJj82ps44PSJ6lMoqKN1Yojl2AzHJ8IeQiIOe7jo9ikipY14bi3MnQZqdmpRprrTH6LEqaH58SeVL0jGMdF309f3b6hC0VlJ9mkD6axvqRaAgEKBg8zsvOpZ6Jjkg/DQd1qVIWF99hO1Afg=
  - secure: VkmyKXkmVu4F+1YwSvacyV+WwvRYvTmbNyvfK/7neot+O0tDO9J0FriUqCwAqW7q/EhrntWTBzkh9ftiVdt5whsJvoEkB1ilVFBO0AELoWhIScJayBSifyh2hboaXRYCuTUXeXA4vq0fv4xg5lZxjxzAR9sHdBHCx5QBLuCjBuns0zXBxA7R2yLmvr3Y/kqoIHvs6VWY3S5PBjXOQcnLzM1TnzjvUWp6x4L5VPqZ/eE1GxaROUqw631ZC4++634mjn+eDsufkYFU947bGXBuceolooBeitiRu22LLdf4oc661fCLBiqCaM7bqQP4b7IR4ZGi3ttK0+CphsJ9wvE68b/5hkQFkoau2dBoxe66hcpYM8qWKuUQGmzGT0OeC5twZvZrCaszrTuPIcoV1q5UKAAIhgZw/YHuYUoRUgL8/ezE69O9u1PMiykXtCjQl2VNthBnnr7yfzGk5B7fAzmjlIZ7HuRZU62/tENqXWa2Hbw0MLkzqCdK0/udu+/nT4Ajf6KrfjEx1qPHvnFq3+T0XL5l33/Wjo5qbsYzucEbSeQS1/oOonBG8who3QyMmMx8ofofZmAI+JHs5YX4z1jHnpoDMzdrLWvqYOmqM6DnFyGHaMWqFPfM54C9YuwRDCdp8jTKc0q0Q3RV6tjklkz4M+D5nIP4Hj0mAuoUtVMAlwk=
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: make callysto/push
  on:
    branch: ianabc
